//Define token types
#define NUMBER 1
#define FLOAT 2
#define EMAIL 3
#define PHONE 4
#define ADDRESS 5
#define C_KEYWORD 6
#define COLON 7
#define IDENTIFIER 8
#define INTEGER 9
#define OP 10
#define FLOATING 11
#define EMAIL_ADD 12
#define PHONE_NUM 13
#define HOME_ADDRESS 14
#define KEYWORD 15
