//Define token types
#define NUMBER 1
#define FLOAT 2
#define EMAIL 3
#define PHONE 4
#define ADDRESS 5
#define COLON 6
#define IDENTIFIER 7
#define INTEGER 8
#define OP 9
#define FLOATING 10
#define EMAIL_ADD 11
#define PHONE_NUM 12
#define HOME_ADDRESS 13
